[tool.poetry]
name = "nedflix"
version = "0.1.0"
description = ""
authors = ["Jeffrey Lazar <jeff.p.lazar@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
h5py = "^3.11.0"
numpy = "^2.0.0"
scipy = "^1.14.0"
tqdm = "^4.66.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
