title = "IceCube"

[properties]

latitude = -90.0 # degrees
longitude = 0.0 # degrees
depth = 1945 # m
medium = "Ice"

[response]

track_effa_file = ""
track_angular_response_file = ""
track_energy_response_file = ""
cascade_effa_file = ""
cascade_angular_response_file = ""
cascade_energy_response_file = ""
